name: Checkmarx Scan

on:
  push:
    branches:
      - main

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build and Test
        run: |
          # Insert your build and test commands here
          
      - name: Run Checkmarx Scan
        run: |
          # Insert Checkmarx scan command here
          
